#!/bin/bash
set -euo pipefail

OUTPUT_PATH="${SRCROOT:-$(pwd)}/VVTerm/Generated/ReviewModeCode.swift"
CODE="${APP_REVIEW_CODE:-}"

if [ -z "$CODE" ]; then
  CODE="VVTERM-REVIEW-2026"
fi

# Escape for Swift string literals (backslash, double-quote, newline).
ESC="${CODE//\\/\\\\}"
ESC="${ESC//\"/\\\"}"
ESC="${ESC//$'\n'/\\n}"

mkdir -p "$(dirname "$OUTPUT_PATH")"
cat >"$OUTPUT_PATH" <<EOF
// Generated by scripts/generate_review_mode_code.sh
// Do not edit manually.

enum ReviewModeCode {
    static let value = "$ESC"
}
EOF
