#!/bin/sh
set -euo pipefail

OUTPUT_PATH="${SRCROOT:-$(pwd)}/VVTerm/Generated/ReviewModeCode.swift"
CODE="${APP_REVIEW_CODE:-}"

if [ -z "$CODE" ]; then
  CODE="VVTERM-REVIEW-2026"
fi

export OUTPUT_PATH
export CODE

python3 - <<'PY'
import os
import json

output_path = os.environ["OUTPUT_PATH"]
code = os.environ["CODE"]

content = (
    "// Generated by scripts/generate_review_mode_code.sh\n"
    "// Do not edit manually.\n\n"
    "enum ReviewModeCode {\n"
    f"    static let value = {json.dumps(code)}\n"
    "}\n"
)

os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, "w", encoding="utf-8") as f:
    f.write(content)
PY
